In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/movies.csv")
df.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [3]:
print(df.isna().sum())

name           0
rating        77
genre          0
year           0
released       2
score          3
votes          3
director       0
writer         3
star           1
country        3
budget      2171
gross        189
company       17
runtime        4
dtype: int64

In [4]:
print(df.budget.isna().sum() / df.shape[0] * 100)

28.31246739697444

In [5]:
matches = df.name.str.contains(r'zodiac', case=False)
df[matches]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
5048,Zodiac,R,Crime,2007,"March 2, 2007 (United States)",7.7,486000.0,David Fincher,James Vanderbilt,Jake Gyllenhaal,United States,65000000.0,84785914.0,Paramount Pictures,157.0

In [6]:
matches = df.name.str.contains(r'harry potter', case=False)
df[matches]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
3843,Harry Potter and the Sorcerer's Stone,PG,Adventure,2001,"November 16, 2001 (United States)",7.6,685000.0,Chris Columbus,J.K. Rowling,Daniel Radcliffe,United Kingdom,125000000.0,1.006968e+09,Warner Bros.,152.0
4047,Harry Potter and the Chamber of Secrets,PG,Adventure,2002,"November 15, 2002 (United States)",7.4,572000.0,Chris Columbus,J.K. Rowling,Daniel Radcliffe,United Kingdom,100000000.0,8.796024e+08,Warner Bros.,161.0
4448,Harry Potter and the Prisoner of Azkaban,PG,Adventure,2004,"June 4, 2004 (United States)",7.9,570000.0,Alfonso Cuarón,J.K. Rowling,Daniel Radcliffe,United Kingdom,130000000.0,7.973616e+08,Warner Bros.,142.0
4643,Harry Potter and the Goblet of Fire,PG-13,Adventure,2005,"November 18, 2005 (United States)",7.7,566000.0,Mike Newell,Steve Kloves,Daniel Radcliffe,United Kingdom,150000000.0,8.966782e+08,Warner Bros.,157.0
5051,Harry Potter and the Order of the Phoenix,PG-13,Action,2007,"July 11, 2007 (United States)",7.5,527000.0,David Yates,Michael Goldenberg,Daniel Radcliffe,United Kingdom,150000000.0,9.421724e+08,Warner Bros.,138.0
5451,Harry Potter and the Half-Blood Prince,PG,Action,2009,"July 15, 2009 (United States)",7.6,492000.0,David Yates,Steve Kloves,Daniel Radcliffe,United Kingdom,250000000.0,9.344541e+08,Warner Bros.,153.0
5652,Harry Potter and the Deathly Hallows: Part 1,PG-13,Adventure,2010,"November 19, 2010 (United States)",7.7,495000.0,David Yates,Steve Kloves,Daniel Radcliffe,United Kingdom,NaN,9.770435e+08,Warner Bros.,146.0
5845,Harry Potter and the Deathly Hallows: Part 2,PG-13,Adventure,2011,"July 15, 2011 (United States)",8.1,790000.0,David Yates,Steve Kloves,Daniel Radcliffe,United Kingdom,125000000.0,1.342322e+09,Warner Bros.,130.0

In [7]:
matches = df.name.str.contains(r'the danish girl', case=False)
df[matches]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
6694,The Danish Girl,R,Biography,2015,"January 22, 2016 (United States)",7.1,170000.0,Tom Hooper,Lucinda Coxon,Eddie Redmayne,United Kingdom,15000000.0,64191523.0,Working Title Films,119.0

In [8]:
matches = df.name.str.contains(r'hobbit', case=False)
df[matches]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
6045,The Hobbit: An Unexpected Journey,PG-13,Adventure,2012,"December 14, 2012 (United States)",7.8,773000.0,Peter Jackson,Fran Walsh,Martin Freeman,New Zealand,180000000.0,1.017004e+09,Metro-Goldwyn-Mayer (MGM),169.0
6253,The Hobbit: The Desolation of Smaug,PG-13,Adventure,2013,"December 13, 2013 (United States)",7.8,615000.0,Peter Jackson,Fran Walsh,Ian McKellen,New Zealand,225000000.0,9.590075e+08,Metro-Goldwyn-Mayer (MGM),161.0
6455,The Hobbit: The Battle of the Five Armies,PG-13,Adventure,2014,"December 17, 2014 (United States)",7.4,487000.0,Peter Jackson,Fran Walsh,Ian McKellen,New Zealand,250000000.0,9.621829e+08,New Line Cinema,144.0

In [9]:
print((df.gross[6455] - df.budget[6455]) / df.budget[6455] * 100)

284.873146

In [10]:
matches = df.name.str.contains(r'prometheus', case=False)
df[matches]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
6051,Prometheus,R,Adventure,2012,"June 8, 2012 (United States)",7.0,578000.0,Ridley Scott,Jon Spaihts,Noomi Rapace,United States,130000000.0,403354469.0,Twentieth Century Fox,124.0

In [11]:
print((df.gross[6051] - df.budget[6051]) / df.budget[6051] * 100)

210.27266846153844